### PR TITLE
Extend Gradle integration test to catch differences in dependencies

### PR DESCRIPTION
**Pull request by jjohannes**
It now fails if the dependencies in Gradle Metadata differ from the dependencies in the corresponding POM.

See: https://github.com/FasterXML/jackson-core/issues/999

### CODE REVIEW

**Comment by jjohannes** [comment]
The test currently fails with these issues which should be fixed in the next Jackson release:

```
  Dependencies of com.fasterxml.jackson.core:jackson-core:2.15.0 are wrong in Gradle Metadata:
    POM:
    Gradle: ch.randelshofer:fastdoubleparser:0.8.0
  Dependencies of com.fasterxml.jackson.jr:jackson-jr-stree:2.15.0 are wrong in Gradle Metadata:
    POM:    com.fasterxml.jackson.core:jackson-core:2.15.0
    Gradle: com.fasterxml.jackson.core:jackson-core:2.15.0, com.fasterxml.jackson.jr:jackson-jr-objects:2.15.0
  Dependencies of com.fasterxml.jackson.module:jackson-module-afterburner:2.15.0 are wrong in Gradle Metadata:
    POM:    com.fasterxml.jackson.core:jackson-core:2.15.0, com.fasterxml.jackson.core:jackson-databind:2.15.0
    Gradle: com.fasterxml.jackson.core:jackson-core:2.15.0, com.fasterxml.jackson.core:jackson-databind:2.15.0, org.ow2.asm:asm:9.4
```

**core** is this: https://github.com/FasterXML/jackson-core/issues/999
**jackson-module-afterburner** is similar (also uses the shade plugin)
**jackson-jr-stree** uses an optional dependencies - that's a bug in the gradle-metadata plugin that is now also fixed in 0.4.0


To fix these:
- Update plugin for all in parent to `0.4.0` - https://github.com/FasterXML/jackson-bom/blob/2.16/base/pom.xml#L182
- In **core** configure the plugin like this:
```
      <plugin>
        <groupId>de.jjohannes</groupId>
        <artifactId>gradle-module-metadata-maven-plugin</artifactId>
        <configuration>
          <removedDependencies>
            <dependency>
              <groupId>ch.randelshofer</groupId>
              <artifactId>fastdoubleparser</artifactId>
            </dependency>
          </removedDependencies>
        </configuration>
      </plugin>
```
- In **jackson-module-afterburner** configure the plugin like this:
```
      <plugin>
        <groupId>de.jjohannes</groupId>
        <artifactId>gradle-module-metadata-maven-plugin</artifactId>
        <configuration>
          <removedDependencies>
            <dependency>
              <groupId>org.ow2.asm</groupId>
              <artifactId>asm</artifactId>
            </dependency>
          </removedDependencies>
        </configuration>
      </plugin>
```

**Comment by cowtowncoder** [comment]
@jjohannes Since I created 2.15 branch, and master is for 2.16.0-SNAPSHOT, could you rebase this to `2.15`? I think we hope to fix the issue for 2.15.1 Jackson release

**Comment by cowtowncoder** [comment]
@jjohannes I think same is also needed for `jackson-module-mrbean` in `jackson-modules-base`.

**Comment by cowtowncoder** [comment]
Fixed for:

* `jackson-bom` (updated version of GMM plugin)
* `jackson-core` (https://github.com/FasterXML/jackson-core/issues/999)

will proceed with Afterburner, Mr Bean.

**Comment by jjohannes** [comment]
Rebase done. Let me know if there is anything else I can help with.

**Review by cowtowncoder — APPROVED** [review]

**Comment by cowtowncoder** [comment]
Looks like `jackson-jr` shading also needs fixing (makes sense) for `jr-stree`; already finding issues.

Although not sure why `jackson-module-mrbean` not included as failure wrt 2.15.0.

**Comment by jjohannes** [comment]
- **jr-stree** - should be fine when you use the `0.4.0` plugin version. It's a bugfix in the plugin. Nothing to do on your side except for publishing a snapshot again with the newer plugin version.
- **jackson-module-mrbean** - the shade plugin is (was?) not configured there to write the minimized POM. The ASM dependency is also still there int the POM: https://repo1.maven.org/maven2/com/fasterxml/jackson/module/jackson-module-mrbean/2.15.0/jackson-module-mrbean-2.15.0.pom
- **Testing against SNASHOT** The test is currently set-up to test against the latest release. It's totally independent of what's in the integration test POM right now. Not sure what's the best general setup would be. Do the following adjustments in `src/test/resources/com/fasterxml/jackson/integtest/gradle/build.gradle.kts` (Line 15 onwards) to test against `2.15.1-SNAPSHOT`:

```
dependencies {
    implementation(platform("com.fasterxml.jackson:jackson-bom:2.15.1-SNAPSHOT"))
}

repositories.maven("https://oss.sonatype.org/content/repositories/snapshots")
repositories.mavenCentral()
```

**Comment by cowtowncoder** [comment]
@jjohannes Ok cool wrt jr-stree. On mrbean I guess I'll need to see diffs from Afterburner's approach.

On SNAPSHOTs that should work for my immediate needs, but I am curious as to where the version by default comes from? (I wouldn't want to hard-code version there; but can leave commented out I think)

**Comment by cowtowncoder** [comment]
@jjohannes With 2.15.1-SNAPSHOT it turns out that:

1. MrBean is complained about (GMM actually excludes Asm fine :) )
2. jr-stree is complained about still

(and `jackson-core` and `jackson-module-afterburner` are resolved now)

**Comment by cowtowncoder** [comment]
Actually GMM is correct for Mr Bean, it's Maven dependencies that are wrong (I did fix Mr Bean and Afterburner both).
So need to address that instead.

**Comment by cowtowncoder** [comment]
@jjohannes I am having some trouble verifying fix via https://github.com/FasterXML/jackson-modules-base/pull/208 -- I can modify `src/test/resources/com/fasterxml/jackson/integtest/gradle/build.gradle.kts` to use version `2.15.2-SNAPSHOT`, but somehow it seems test downloads older (3 day old) snapshot version instead of newly deployed one. I cleared local Maven cache, but wondering if Gradle might have some cache of its own.

**Comment by cowtowncoder** [comment]
Looks like new version is now available, and failure is resolved.

**Pull request merged**
